services:
    db:
        image: mysql
        container_name: mysql-rehber
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_ROOT_HOST: '%' 